#ifndef AURORA_SHELL_CONTRACT_H
#define AURORA_SHELL_CONTRACT_H

#define AURORA_PIXEL_SCALE_MIN 1
#define AURORA_PIXEL_SCALE_MAX 4
#define AURORA_TITLEBAR_HEIGHT_PX 24
#define AURORA_TASKBAR_HEIGHT_PX 32
#define AURORA_ICON_SIZE_SMALL_PX 16
#define AURORA_ICON_SIZE_MEDIUM_PX 32
#define AURORA_ICON_SIZE_LARGE_PX 48

enum aurora_shell_surface {
    AURORA_SURFACE_DESKTOP,
    AURORA_SURFACE_TASKBAR,
    AURORA_SURFACE_START_MENU,
    AURORA_SURFACE_NOTIFICATION_CENTER,
    AURORA_SURFACE_CONTEXT_MENU
};

enum aurora_shell_sound {
    AURORA_SOUND_CLICK,
    AURORA_SOUND_ERROR,
    AURORA_SOUND_LOGIN,
    AURORA_SOUND_LOGOUT
};

#endif
